version: "3"

networks:
  default: ~
  traefik:
    external: true

services:
  bdd:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=web_matura
    ports:
      - "3320:3306"
    networks:
      default: ~
      traefik: ~

  php:
    build: docker/php
    volumes:
      - .:/var/www:rw,cached
      - ./public:/var/www/public:rw,delegated
    networks:
      default: ~
      traefik: ~

  nginx:
    build: docker/nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.matura.rule=Host(`matura.devyour.cloud`)"
      - "traefik.http.routers.matura.entrypoints=web"
      - "traefik.http.routers.matura-secure.rule=Host(`matura.devyour.cloud`)"
      - "traefik.http.routers.matura-secure.tls=true"
      - "traefik.http.routers.matura-secure.entrypoints=websecure"
    volumes:
      - ./public:/var/www/public:ro
    depends_on:
      - php
    ports:
      - 8083:80
    networks:
      default: ~
      traefik: ~
