imports:
  - { resource: name_generator.yaml }

parameters:
  trusted_device_version: 1
  cookie_lifetime: 365 #days
  token_lifetime: 30 #days
  access_code_duration: "PT15M"
  encryption_key: "%env(APP_ENCRYPTION_KEY)%"
  trusted_device_cookie_name: "_trusted_device"
  trusted_device_header_name: "x-trusted-device"

services:
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    bind:
      $trustedDeviceCookieName: "%trusted_device_cookie_name%"
      $trustedDeviceHeaderName: "%trusted_device_header_name%"
      $appHost: "%env(APP_HOST)%"
      $cookieLifetime: "%cookie_lifetime%"

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
      - "../src/Tests/"

  App\Service\EncryptionService:
    arguments:
      $salt: "%env(APP_SECRET)%"
      $trustedDeviceVersion: "%trusted_device_version%"
      $tokenLifetime: "%token_lifetime%"
      $secretKey: "%encryption_key%"

  App\Service\NameGeneratorService:
    arguments:
      $names: "%name_generator%"
      $adjectives: "%adjective_generator%"
